### ISSUE TITLE
Concurrent map write in ssh agent code

### ISSUE THREAD

**Issue by seveas** [seveas/herd#62]
```
herd run app=xxx role=yyy -- uptime                                                                                                                                                                                               
Waiting (0s/1m0s)... 0/8 done, 8 in progress, 0 ok, 0 fail, 0 errorfatal error: concurrent map writes

goroutine 26 [running]:
github.com/seveas/herd/ssh.(*agent).SignersForPath(0x1400004c960, {0x1401b5f3a70, 0x26})
        /private/tmp/herd-20241210-74971-uoime0/herd-0.13.1/ssh/agent.go:271 +0x314
github.com/seveas/herd/ssh.(*Executor).connect.(*agent).SignersForPathCallback.func3()
        /private/tmp/herd-20241210-74971-uoime0/herd-0.13.1/ssh/agent.go:237 +0x30
golang.org/x/crypto/ssh.publicKeyCallback.auth(0x0?, {0x1401bd882e0, 0x20, 0x20}, {0x1400052212e, 0x7}, {0x10208abc0, 0x14000a48000}, {0x102082080, 0x140001704c0}, ...)
        /Users/oliikit/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/client_auth.go:308 +0x54
golang.org/x/crypto/ssh.(*connection).clientAuthenticate(0x1400af7ed00, 0x14000b80270)
        /Users/oliikit/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/client_auth.go:72 +0x2c8
golang.org/x/crypto/ssh.(*connection).clientHandshake(0x1400af7ed00, {0x1401bc86000, 0xe}, 0x14000b80270)
        /Users/oliikit/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/client.go:113 +0x274
golang.org/x/crypto/ssh.NewClientConn({0x102092ed8, 0x14000bb4010}, {0x1401bc86000, 0xe}, 0x14000130820)
        /Users/oliikit/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/client.go:83 +0x110
golang.org/x/crypto/ssh.Dial({0x10198475c?, 0x0?}, {0x1401bc86000, 0xe}, 0x14000130820)
        /Users/oliikit/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/client.go:181 +0x48
github.com/seveas/herd/ssh.(*Executor).connect.func2()
        /private/tmp/herd-20241210-74971-uoime0/herd-0.13.1/ssh/executor.go:135 +0x48
created by github.com/seveas/herd/ssh.(*Executor).connect in goroutine 40
        /private/tmp/herd-20241210-74971-uoime0/herd-0.13.1/ssh/executor.go:133 +0x4e0
```

This happens because any thread can write to the signersByPath map. When rewriting the agent code this must be fixed.

**Comment by seveas** [comment]
Fixed indirectly in #74
